import { Urbanist } from "next/font/google";
import "./globals.css";
import Navbar from "@/Components/Navbar";

const urbasint = Urbanist({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={urbasint.className}>
        <Navbar />
        {children}
      </body>
    </html>
  );
}
